### ISSUE TITLE
API inconsistency

### ISSUE THREAD

**Issue by ghost** [rust-lang/wg-allocators#104]
According to the https://doc.rust-lang.org/alloc/alloc/trait.Allocator.html#required-methods, `Allocator::alocate` on success returns `NonNull<[u8]>`, but` Allocator::deallocate` takes `NonNull<u8>` instead of `NonNull<[u8]>`. It looks inconsistent. Is it design problem or there are something that I misunderstood?

**Comment by CAD97** [comment]
So the *reason* for this is that the allocation size is given to `deallocate` in `Layout`. `allocate` returns `NonNull<[u8]>` because it could give you more memory than requested.

**Comment by ghost** [comment]
Thank you, that makes sense.
