### ISSUE TITLE
BTreeMap::new_in should be const

### ISSUE THREAD

**Issue by Kritzefitz** [rust-lang/wg-allocators#118]
The title basically already says it all. `alloc::collections::btree_map::BTreeMap::new_in` is currently not marked as `const`, even though there doesn't seem to be a good reason why it shouldn't be.

**Comment by Amanieu** [comment]
Sounds good! Feel free to submit a PR and assign it to me for review.

**Comment by Kritzefitz** [comment]
If I'm not mistaken, the merged PR fixes this issue.
