### ISSUE TITLE
Question: protocol around Allocator::grow

### ISSUE THREAD

**Issue by yanchith** [rust-lang/wg-allocators#126]
UPDATE: turns out I read the code too hastily. RawVec actually doesn't retry. The rest of the question stands, though.

Some collections support in-place growing with Allocator::grow. ~Vec (via RawVec) first attempts to grow, and if that fails, attempts to reallocate.~

~This seems reasonable to me, because the allocator may refuse to grow an allocation, if it can't do it efficiently, and RawVec tries again if growing fails.~

Should collections generally retry by calling Allocator::allocate, if Allocator::grow failed? If so, should we document it in the allocator trait? Arguably, it is somewhat documented by the "or if growing otherwise fails" text, but it would be nice to know that the collection should attempt to call allocate itself, if growing failed.

**Comment by yanchith** [comment]
I think I was a little confused when I wrote this. Now I realize, Allocator::grow is basically realloc, and it decides what to do internally. This means that when it fails, Allocator::allocate is going to fail as well.

**Comment by WorldSEnder** [comment]
Same question. While the current impl is indeed a realloc, I don't see why all allocators should be forced to implement a `allocate()+memcpy()+free()` "cold" path on behalf of the user and I'd wish that the `RawVec` would do this on its own (and there was a way to communicate this in the return type of `grow()`).
