### ISSUE TITLE
Rc and Arc are missing new_cyclic_in

### ISSUE THREAD

**Issue by matthewpipie** [rust-lang/wg-allocators#132]
new_cyclic was added in Rust 1.60 and allows users to create cyclic data structures without unsafe code; however, there is no equivalent new_cyclic_in. If this is an oversight, I'm happy to make a PR.

**Comment by Amanieu** [comment]
Yes, this does seem to be an oversight, feel free to make a PR.

**Comment by matthewpipie** [comment]
Great, I made a PR here: https://github.com/rust-lang/rust/pull/129674. 

I have a few outstanding questions in that PR. If you wouldn't mind taking a look at that, it would be much appreciated. I'm very new to the standard library and don't know some of its conventions.

**Comment by matthewpipie** [comment]
Bump! Would love some feedback on if that PR is done appropriately.

**Comment by zakarumych** [comment]
PR is still marked as "draft".

**Comment by matthewpipie** [comment]
Thank you, fixed!

**Comment by matthewpipie** [comment]
Merged!
