### ISSUE TITLE
Add best-effort `owns` method?

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/wg-allocators#52]
`AllocRef` should have an `owns` method for determining if a particular allocation came from specific allocation. Obviously, many allocators couldn't know for sure, so it would have to be best effort.

```rust
fn owns(&self, ptr: NonNull<u8>, layout: Layout) -> bool;
```

or

```rust
pub enum Owns {
    Yes,
    Maybe,
}

fn owns(&self, ptr: NonNull<u8>, layout: Layout) -> Owns;
```

This could be very useful for implementing combinatorial allocators, like in https://www.youtube.com/watch?v=LIb3L4vKZ7U.

**Comment by Amanieu** [comment]
This was previously discussed here: https://github.com/rust-lang/rust/issues/44302

The conclusion was that it isn't implementable (or at least not efficiently) for the majority of allocator designs. This is best left to a separate trait for allocators that specifically support composability.

**Comment by lachlansneff** [comment]
Ah, that makes sense.
