### ISSUE TITLE
Add `Result` to `core::alloc`

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/wg-allocators#56]
What to you think about adding a `Result` alias to the alloc module?

```rust
pub type Result<T, E = AllocErr> = core::result::Result<T, E>;
```

or even

```rust
pub type Result<T = MemoryBlock, E = AllocErr> = core::result::Result<T, E>;
```

**Comment by SimonSapin** [comment]
My the `E` parameter? There isn’t one in `std::io::Result` or `std::thread::Result`. Shouldn’t users that would make it non-default be using `result::Result` instead?

**Comment by TimDiekmann** [comment]
I don't have a strong opinion on the default parameter, but IMO they are missing in `io::Result`, `thread::Result`, and `fmt::Result`. 

Anyway, if I use a defaulted Result, I always use the module name as well for clarity:
```rust
use io;
fn foo() -> io::Result
```

**Comment by TimDiekmann** [comment]
Inspecting `io::Result` again:

> This typedef is generally used to avoid writing out `io::Error` directly and is otherwise a direct mapping to `Result`.

Do we also want to rename `alloc::AllocErr` to `alloc::Error`?

**Comment by SimonSapin** [comment]
There’s also `alloc::LayoutErr`.

**Comment by TimDiekmann** [comment]
Oh, right :disappointed:

**Comment by Amanieu** [comment]
I don't feel that `Result<T, AllocErr>` is sufficiently widely used to justify making a type alias.
