### ISSUE TITLE
Move `core::alloc::MemoryBlock` to `core::mem::Block`?

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/wg-allocators#60]
Similar to #59, but less complicated, as `MemoryBlock` is gated behind `allocator_api`.

**Comment by Amanieu** [comment]
I feel that this should stay in `alloc` since it is pretty tied to memory allocation.

**Comment by TimDiekmann** [comment]
It's currently used only for allocation, yes, but this also applies to #59. This is why I'm asking :slightly_smiling_face:

**Comment by TimDiekmann** [comment]
Closed for the same reason as in https://github.com/rust-lang/rust/pull/71856
