### ISSUE TITLE
Hide Cow implementation details

### ISSUE THREAD

**Issue by pickfire** [rust-lang/wg-allocators#67]
[Cow](https://doc.rust-lang.org/stable/alloc/borrow/enum.Cow.html) is implemented with implementation details, can we add additional layers on top of it to allows other Cow ripoffs such as https://github.com/maciejhirsz/beef to easily become a Cow drop-in replacement without changing anything?

Currently, `Cow` is accessed through the fields directly, we could add additional methods to access those fields and soft deprecate the existing direct access to the enum fields. Any thoughts on this?

**Comment by TimDiekmann** [comment]
I think this should go to [rust-lang/rust](https://github.com/rust-lang/rust), as this workgroup's main issue is the [allocator-api](https://github.com/rust-lang/rust/issues/32838) feature.
