### ISSUE TITLE
Rename `AllocRef` to `Allocator` and `alloc` to `allocate`

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/wg-allocators#76]
With rust-lang/rust#77187 we released `AllocRef` to the wild. It was pointed out, the names `AllocRef` and `alloc` are confusing sometimes. The main reason for this, is, that "alloc" is used as a verb **and** as a noun.

in https://github.com/rust-lang/rust/pull/77187#discussion_r511169783 @Aaron1011 noted, that:
> [`Box::alloc_ref`] sounds like we're allocating a reference, not obtaining a reference to the allocator.

However, `alloc_ref` is the lowercased name of the Trait. @Amanieu also suggested, to rename it to `Box::allocator`, but the term `allocator` is never used anywhere, so I decided to stick with `alloc_ref` for now.

I think, it makes sense, to rename `AllocRef` to `Allocator` and `(de)alloc` to `(de)allocate`. The main reason for calling it `AllocRef` instead of `Alloc` was, that we wanted to express, that `AllocRef` should be a ZST or a reference to the actual allocator (not a reference to an "alloc" :wink: ). This however is also pointed out in the documentation and we don't expect many people to implement an allocator.
A very minor downside is the longer name of `Allocator` and `allocate`, but it's way more clear, if you read those terms. The trait will also not be used often directly. In most cases, it will simply be passed to `Box` or `Vec`. So most people neither have to call `allocate` or `deallocate`, nor have to import `Allocator` into scope. They probably won't even care, how the allocator is implemented (ZST or reference) as long they can simply pass an allocator to those structs.

This proposal also includes renaming `Box::alloc_ref` to `Box::allocator`.

cc @Amanieu @Lokathor @Wodann @CAD97 @scottjmaddox @vertexclique

**Comment by Wodann** [comment]
When reviewing the PR, I couldn't help but wonder whether people had similar confusions about whether `AllocError` is an allocation error or an error type for allocators.

I know this goes beyond the scope of the original proposal, but since we are asking ourselves the question; I'm wondering whether there are more instances that might be ambiguous?

**Comment by TimDiekmann** [comment]
Hmm, isn't `AllocError` both an allocation error and the error type for allocators? :smile: 
The more I play around with the `Allocator` trait, the more I think, that the error should be associative but I leave this question open (and #23 closed) until I finished some work with the [storage-approach for collections](https://internals.rust-lang.org/t/is-custom-allocators-the-right-abstraction/13460) but the concerns are very valid IMO.

> I know this goes beyond the scope of the original proposal, but since we are asking ourselves the question; I'm wondering whether there are more instances that might be ambiguous?

Do you have something in mind specifically?

**Comment by Wodann** [comment]
I think I'm too close to the subject matter to not be confused by it, but I think @aaron1011's original point was very valid. So maybe they can speak from experience?
