### ISSUE TITLE
Allocator doesn't seem to be implemented for Arc<A>

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/wg-allocators#84]
This has obvious usecases.

```rust
impl<A: Allocator + ?Sized, B: Allocator> Allocator for Arc<A, B> {
    ...
}
```

**Comment by TimDiekmann** [comment]
This was already proposed in https://github.com/rust-lang/wg-allocators/issues/54, however the `Rc` and `Arc` part were removed as the allocator had to be mutable. I changed back the proposal to include it again.
