### ISSUE TITLE
Generalize the Write impl for `Vec<u8>` to `Vec<u8, A>`

### ISSUE THREAD

**Issue by athre0z** [rust-lang/wg-allocators#86]
I'd like to generalize the [`Write` impl for `Vec<u8>`](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-Write) to `Vec<u8, A>`. Is there any reason for not doing this? I suspect that this impl might simply have been forgotten because it lives in the `io` module rather than by the other trait impls for `Vec`?

**Comment by TimDiekmann** [comment]
Please go ahead, I think I simply forgot to implement it. 🙂

**Comment by athre0z** [comment]
Excellent — I created a PR over at https://github.com/rust-lang/rust/pull/82862!

**Comment by athre0z** [comment]
Aaaand it's merged! I'd like to use this chance to thank you (and everyone else involved with this!) for your work on `allocator_api`. I think that this gets a lot less attention than it deserves. Particularly for gracefully working with arena allocators, this is **super** important to have!

**Comment by ChayimFriedman2** [comment]
I think we need to check if we have other forgotten impls. A simple way will be to just remove the default type for `A` and search for compiler errors.
