### ISSUE TITLE
Should most allocators be Clone?

### ISSUE THREAD

**Issue by shlevy** [rust-lang/wg-allocators#88]
I'm creating a data structure that includes `Box`es and `Vec`s and `Vec`s of `Box`es, and I find myself between two choices:

1. Have the top-level data structure own the `Allocator` and have each nested structure use the free `&A` implementation
2. Require the `Allocator` to be `Clone` and just `clone` it at each usage point

Based on this section in the docs:

> cloning or moving the allocator must not invalidate memory blocks returned from this allocator. A cloned allocator must behave like the same allocator

it seems like the expected pattern is 2, and that therefore most allocators will be `Clone`. Is that correct?

**Comment by Amanieu** [comment]
`hashbrown` also requires allocators to be `Clone`. In practice I would expect the vast majority of allocators to be `Clone`.

**Comment by RustyYato** [comment]
Note that you can always create a `Clone` allocator by using `&T`. So the `Clone` bound is strictly more general, as it also allows non-`&T` allocators.

**Comment by cmazakas** [comment]
In general, yes.

Allocators should generally be a cheap-to-copy handle to an upstream memory resource.

**Comment by shlevy** [comment]
Seems like there's consensus, thanks!
