### ISSUE TITLE
Explicitly mention in the docs that `grow`, `grow_zeroed`, and `shrink` have to handle changes in alignment

### ISSUE THREAD

**Issue by autumnontape** [rust-lang/wg-allocators#97]
The docs currently imply that the alignment of `new_layout` may be different from that of `old_layout` by not stating otherwise. Reallocations with altered alignments are extremely uncommon; I had to track down #5 in this repository to convince myself this wasn't a mistake. This could be a pitfall for implementors of `Allocator` if it's not made more explicit.

**Comment by Amanieu** [comment]
Sounds good, would you be willing to make a PR to rust-lang/rust to update the documentation?

**Comment by autumnontape** [comment]
Sure! I can probably do that a few hours from now.

**Comment by autumnontape** [comment]
I've opened https://github.com/rust-lang/rust/pull/95546.

**Comment by autumnontape** [comment]
https://github.com/rust-lang/rust/pull/95546 was merged!
